### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by walkah** [EtienneLem/atom-rdio#8]
It looks like this package no longer works with recent versions of atom. Checked atom-spotify and it appears to have a similar issue ( https://github.com/jakemarsh/atom-spotify/issues/14 )... but I don't use spotify.

The current track doesn't show in the status line and none of the commands seem to have any effect.

Atom version: 0.169.0
Rdio Version: 2.38
Mac OS 10.10.1

**Comment by EtienneLem** [comment]
Thanks for reporting, I’ll give it a look ASAP.

**Comment by benogle** [comment]
The atom status-bar API has changed: https://github.com/atom/status-bar
