### ISSUE TITLE
Failed to load the Rdio package

### ISSUE THREAD

**Issue by sroberts** [EtienneLem/atom-rdio#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.2
**Thrown From**: [Rdio](https://github.com/EtienneLem/atom-rdio) package, v0.5.1

### Stack Trace

Failed to load the Rdio package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/sroberts/.atom/packages/Rdio/lib/rdio-view.coffee:5:199)
    at /Users/sroberts/.atom/packages/Rdio/lib/rdio-view.coffee:16:5
    at Object.<anonymous> (/Users/sroberts/.atom/packages/Rdio/lib/rdio-view.coffee:191:5)
    at Object.<anonymous> (/Users/sroberts/.atom/packages/Rdio/lib/rdio-view.coffee:193:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Rdio, v0.5.1
autocomplete-plus, v2.12.0
dash-on-cursor, v0.1.0
file-icons, v1.5.4
go-plus, v3.3.6
jsonlint, v1.1.0
linter, v0.12.1
linter-pyflakes, v0.0.4
linter-write-good, v0.4.2
regex-railroad-diagram, v0.7.4

# Dev
No dev packages
```

**Comment by niftyn8** [comment]
Having issues with this on 1.0 too.

**Comment by michaelhelmick** [comment]
+1

**Comment by EtienneLem** [comment]
I’m very sorry about that guys, I don’t when I’ll have time to fix it. Haven’t been using neither Atom nor Rdio for the past few months.

Hopefully I find time to fix soon!

**Comment by michaelhelmick** [comment]
@EtienneLem Thanks! I'd take a whack at it if I need CoffeeScript :x

**Comment by michaelhelmick** [comment]
@EtienneLem As mentioned in https://github.com/EtienneLem/atom-rdio/issues/8, it looks like the status bar API has changed. I went down a rabbit hole (with no knowledge of coffee script) and seemed to be a little work. I'm guessing it's not and I was making it more than it was. But would love to see an update :) will gittip :D

**Comment by michaelhelmick** [comment]
On a third note, looks like https://github.com/albertorestifo/atom-spotify2/blob/master/lib/atom-spotify.coffee implements Status Bar correctly. Maybe a fork of that repo suited for Rdio would suffice?

**Comment by EtienneLem** [comment]
Yeah, atom-rdio was built with a very early version of Atom. Will have to look at the status bar API and update accordingly.

Will have a look tonight-ish OR next week at the latest.

**Comment by michaelhelmick** [comment]
Thank you!

**Comment by sroberts** [comment]
:metal:
